package com.company.persistence;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.company.domain.ItemVO;
import com.company.mapper.ItemMapper;

import lombok.extern.log4j.Log4j;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("file:src\\main\\webapp\\WEB-INF\\spring\\root-context.xml")
@Log4j
public class ItemMapperTest {
	@Autowired
	private ItemMapper mapper;
	
	@Test
	public void testRead() {
		var items = mapper.findAll();
		assertNotNull(items);
		assertTrue(items.size() > 0);
	}
	
	@Test
	@Transactional
	public void testInsertUpdate() {
		ItemVO item = testItem();
		assertTrue(mapper.insert(item) > 0);
		long idx = item.getIdx();  
		assertTrue(idx > 0);
		
		assertNotNull(mapper.findByIdx(idx));
		
		item.setShortDesc("shortttt");
		item.setLongDesc("LONG");
		item.setPrice(123456888);
		item.setOriginalPrice(888654321);
		assertTrue(mapper.update(item) > 0);
		assertTrue(mapper.reduceItemQuantity(idx, 3) > 0);
	}
	
	private ItemVO testItem() {
		ItemVO itemVO = new ItemVO();
		itemVO.setName("Oh TEST");
		itemVO.setBaseImgUrl("202501_SLASH_TEST");
		itemVO.setShortDesc("short short short");
		itemVO.setLongDesc(testText());
		itemVO.setOriginalPrice(300200);
		itemVO.setPrice(100000);
		itemVO.setStock(55);
		itemVO.setProviderIdx(1);
		// assume that provider 1 exists, which is generated by sql
		return itemVO;
	}
	private String testText() {
		return "The only way to do great work is to love what you do. - Steve Jobs. " +
	            "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost. " +
	            "To be, or not to be, that is the question. - William Shakespeare. " +
	            "Life is what happens when you're busy making other plans. - John Lennon. " +
	            "It is never too late to be what you might have been. - George Eliot. " +
	            "In the end, it's not the years in your life that count, it's the life in your years. - Abraham Lincoln. " +
	            "You must be the change you wish to see in the world. - Mahatma Gandhi. " +
	            "Not all those who wander are lost. - J.R.R. Tolkien. " +
	            "The only thing we have to fear is fear itself. - Franklin D. Roosevelt. " +
	            "The journey of a thousand miles begins with one step. - Lao Tzu. " +
	            "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson. " +
	            "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde. " +
	            "You only live once, but if you do it right, once is enough. - Mae West. " +
	            "Do what you can, with what you have, where you are. - Theodore Roosevelt. " +
	            "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill. " +
	            "Life isn't about finding yourself. It's about creating yourself. - George Bernard Shaw. " +
	            "Be the change that you wish to see in the world. - Mahatma Gandhi. " +
	            "I am not what happened to me, I am what I choose to become. - Carl Jung. " +
	            "Imagination is more important than knowledge. - Albert Einstein. " +
	            "The best way to predict the future is to create it. - Peter Drucker. " +
	            "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau. " +
	            "It is our choices that show what we truly are, far more than our abilities. - J.K. Rowling. " +
	            "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson. " +
	            "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar.";
	}
}
